### ISSUE TITLE
[1.12.2] 8.0.0 Crash with Forge 2811 - Betweenlands Compatibility

### ISSUE THREAD

**Issue by MokahTGS** [FossilsArcheologyRevival/FossilsArcheologyRevival#1124]
Getting a crash with the 1.12.2 version trying to launch it within a mod pack.

Forge 2811
FossilArch 8.0.0
LLib 1.7.17-1.12.2

Full mod list: https://pastebin.com/5qPRKz0R

Crash Log: https://paste.dimdev.org/ifoximudeb.mccrash

**Comment by LemonJamTart** [comment]
Yeah, it's a Betweenlands incompatibility. It's been brought up several times but hasn't yet been addressed by the devs as far as I know.

**Comment by TheCyberBrick** [comment]
I believe the reason for this is that write a `FluidStack` to NBT will crash when no world was loaded yet.  
While writing to NBT it calls `FluidStack#getFluid()` which again calls `fluidDelegate.get()`.  
Since the world wasn't loaded yet the delegate will just return the fluid that it is the delegate of. In this case it seems the BL registered the tar fluid first, hence it is the *only* tar fluid that is added to `FluidRegistry#fluid` (see `FluidRegistry#registerFluid(Fluid)`).  
Now when F/A tries to write a `FluidStack` of its own tar fluid to NBT the writing to NBT then calls `fluidDelegate.get()` on the delegate of the F/A tar fluid which just returns the F/A tar fluid, then it calls `FluidRegistry.getName(fluid)` with the F/A tar fluid which will end up returning `null` since only the BL tar fulid is added to `FluidRegistry#fluid`.  
Changing `FluidStack fluidContents = new FluidStack(FAFluidRegistry.TAR_FLUID, bucket.getCapacity());` to `FluidStack fluidContents = new FluidStack(Fluid.getFluid(FAFluidRegistry.TAR_FLUID.getName()), bucket.getCapacity());` in your `FARecipeRegistry #blocks()` should fix this I think.

**Comment by LemonJamTart** [comment]
Thanks you for your help! But how would I edit the class file in the first place?

**Comment by Hunter52901** [comment]
so is there a way to fix this?

**Comment by 4f6f3b** [comment]
Thanks, @TheCyberBrick, we'll try that.

@LemonJamTart @Hunter52901 Just be a little patient and we'll get this rolled into an update.

**Comment by MokahTGS** [comment]
Woot!
