### ISSUE TITLE
Swamp Issue?

### ISSUE THREAD

**Issue by AwsomeRod** [FossilsArcheologyRevival/FossilsArcheologyRevival#1267]
I am unsure if it is the mod or something else, but every time I go to a swamp biome, my game freezes that I have no choice but to force quit. It only happens in the swamp biome, otherwise, it runs well.

**Comment by josephgilbert** [comment]
I believe I'm having the same problem as well.  What other mods are you using alongside F&A?  I'm assuming in your case the game starts to have lag in the swamps that causes intense rubber banding and NPCs stop moving around?

**Comment by josephgilbert** [comment]
So, I did some testing myself.  I created a custom world in creative mode (the issue occurs in both survival and creative) without any of the other mods I installed when I began to experience this issue.  I started to fly around testing to see if the world would eventually lag itself to death.  It did, but what's interesting is that it lagged out ONLY when I was around a tar pit with two tar slimes.  This leads me to believe the issue is something to do with the tar slimes in the swamps and not the swamps themselves.

**Comment by lindstheginj** [comment]
@AwsomeRod @josephgilbert are you still experiencing this in 8.0.1?

**Comment by josephgilbert** [comment]
I can't say that I've been in a situation in 8.0.1 where tar slimes spawned in the swamp (simply because I disabled tar pits and the slimes via the config file).  I can say that there is another issue I've been having.  It may not be the most appropriate place to discuss it, however the analyzers seem to have trouble analyzing biofossils.  The progress bar keeps going as if it does work, but I'd say 85-90% of the time, the fossils don't get successfully analyzed, and return nothing at all.  I don't know if this is because I'm using a world that previously had F&A 8.0.0 on it or what, but that's about the only reason I can think of for this problem occurring besides maybe something to do with feeding items into analyzers and taking out items via hoppers.  Thank you for asking about the swamp issue however.


________________________________

**Comment by lindstheginj** [comment]
In the future, please keep separate bugs on their own threads. The analyzer bug has actually been reported already, and we’r working on it :)

**Comment by josephgilbert** [comment]
I apologize, and I'm very happy to hear that the bug is being worked on!  Keep up the awesome work!


________________________________

**Comment by darthvader45** [comment]
If you're talking about slimes causing rubber-banding and lag, got it happening in 8.0.3 as well. Damned slimes killed my world.  I literally cannot go to swamps anymore because of this.  WHY?
