### ISSUE TITLE
sometimes tiktaaliks don't move on land 

### ISSUE THREAD

**Issue by magicpenguinbones** [FossilsArcheologyRevival/FossilsArcheologyRevival#1384]
they don't sleep,but they sit and sit and sit and if you move them into the water, they start moving again.

**Comment by lindstheginj** [comment]
May be related to #1368 
@magicpenguinbones can you test to see if this is just a problem with males, or if females and babies seem to have the same issue?

**Comment by Adsper** [comment]
I think the issue here is that when the tiktaalik tries to get into water from land, it somehow gets stuck on the edge of the water block. As soon as the bubbles that show a mob has entered water appear, the tiktaalik will just stop.
![2019-07-17_20 14 10](https://user-images.githubusercontent.com/11862143/61426534-900d5400-a8cf-11e9-8bbd-211bc1e26aae.png)
