### ISSUE TITLE
Too Many Structures Spawning

### ISSUE THREAD

**Issue by Animalover609** [FossilsArcheologyRevival/FossilsArcheologyRevival#1387]
![FnAR Picture](https://user-images.githubusercontent.com/51711581/59281557-607b8400-8c5f-11e9-97cc-a3c871cac6d2.png)

I think these are structures from this mod, and I don't think this is supposed to happen. There were even more if I turned around. Thank you.

**Comment by Animalover609** [comment]
![FnAR Picture 2](https://user-images.githubusercontent.com/51711581/59282646-28754080-8c61-11e9-8cf6-c44624099b70.png)
 
Slightly better picture to show what's happening. If it helps, I'm on MC 1.12.2 and F&A 8.0.1. I have some other mods installed such as ZAWA, HWYLA, Better Animal Models, Sophisticated Wolves, Quark, and Xaero's Minimap.

**Comment by sa13103** [comment]
ive been running into the same issue, through ive noticed it only seems to happen with they aztex/myan style structures. ill keep looking as i travel about to see if this occurs with other structures from fossils.

**Comment by lindstheginj** [comment]
Mushroomsock had a good explanation about why this occurs: "The jungle ones being too common is because in actual jungles there's not many places they can spawn with all the trees and stuff so they have to spawn almost whenever they get the chance, which means when you get biome mods which have jungles without so much clutter they spawn everywhere."

**Comment by 0dinson** [comment]
I want to add that while the explanation makes sense for why it happens regarding too many spawns, it doesn't directly explain why the spawn behavior is so extremely off for everything else too. I know Minecraft itself isn't perfect and villages in 1.12 still spawn extremely weird. 

But in this mod even the desert library which is a desert building so alot of free space with alot of flat ground the mod still manages to spawn them completely bugged/off. Inside the ground, on small hills so they mostly float, on one high flats so the bottom layer from the garden is simply missing and the water is running everywhere, etc.. 

I really hope you find a solution for this because I love the buildings but the spawns are so extremely off for every single one that it ruins any landscape.

**Comment by Bastion14** [comment]
I run into this problem too. They also still spawn when structures are turned off. They spawn in water, trees, or anywhere they like.

**Comment by Alex-the-666** [comment]
should be fixed
