### ISSUE TITLE
[Request] config option to allow in-world spawning

### ISSUE THREAD

**Issue by Zygus42** [FossilsArcheologyRevival/FossilsArcheologyRevival#1463]
Would love to have an option in the config to allow the mobs to spawn in the world instead or as well as having to be resurrected via tech.  I would suggest would spawn like animal mobs and not despawn, instead of spawning like zombies etc.

**Comment by Angery-Balaur** [comment]
Devs are planning a big dimension update for that very purpose, so they don't intend on ever making the mobs spawn in the overworld. I think your best bet would be to figure out how to make an add-on for it (That's how mob spawning in the overworld was done back in 1.7 minecraft, some dude made an add-on, but obviously that old add-on won't work anymore because of the code rewrite of the port)

**Comment by Angery-Balaur** [comment]
Ah wait I can't close threads.
