### ISSUE TITLE
8.0.3 Completely busted modded server

### ISSUE THREAD

**Issue by LemonJamTart** [FossilsArcheologyRevival/FossilsArcheologyRevival#1559]
Hi! A friend and I run a private modded server, and we recently added Fossils and Archaeology Revival 8.0.3 to our modlist. Unfortunately, this was a mistake, because upon loading into the world we discovered that a whole smorgasbord of blocks had been switched around. Neither of us had ever had that happen before, and F&A was the only mod we had added, so we're kind of at a loss. I have the server log [here](https://pastebin.com/0bQ2LurL). As you can see, shortly after I joined and saw what happened to our house, the server crashed. Full modlist is [here](https://pastebin.com/cup9wrhf). The mods I noticed were affected, at least in our house, were Tinker's Construct, The Betweenlands, Forestry, Ice and Fire, Pam's Harvestcraft, and Chisel & Bits. I have put several screenshots of the carnage down below. I got the Before screenshots from a backup we luckily made before adding F&A, and the After screenshots from the _same_ backup world file that I loaded into Singleplayer with F&A on.
[Before](https://imgur.com/a/FPAestg)
[After](https://imgur.com/a/6TcDqnb)

**Comment by Alex-the-666** [comment]
> crash-2019-09-29_20.06.42-server.txt
do you have this file?

Also, as for the block jumble I have no clue how that happened as there should be nothing in F/A capable of doing that. Perhaps there is some sort of mod conflict?

**Comment by SuspiciousMango** [comment]
Alex would definitely know more about this than I would because he works with forge regularly, but I've had similar issues in the past. Sometimes forge just says nope and switches around all of your block ids. It happens to me most frequently when I try to move a world file from one computer to another (running the same version of the same modpack and everything) but even rarer I've had it happen on the same computer just switching between save files. It seems that forge has no consistency for its data values and sometimes just randomly switches what block gets what id. Hence the random swapping of blocks around your world. As for a fix, I'm not aware of one
