### ISSUE TITLE
Betweenlands Tar Issue

### ISSUE THREAD

**Issue by mxnmnm** [FossilsArcheologyRevival/FossilsArcheologyRevival#1611]
fossils 8.0.3

When tar is picked up in a bucket it turns into a betweenlands tar bucket which causes it to have no texture.  This also removes the custom tar bucket from the betweenlands.  Picking up the fossils tar and placing it back down always results in it turning into betweenlands tar.  I'm guessing it might have to do with the fact they're both named tar.  Maybe rename fossils and archeology tar into Fossil Tar or something like that.

https://imgur.com/a/FAGh0AS

**Comment by Z-Tunic** [comment]
Perhaps related.
https://github.com/Angry-Pixel/The-Betweenlands/issues/872

Fossil's Tar spawns Tar Slimes and it acts like quicksand making it difficult to escape from where with Betweenlands Tar it is kinda 'swim-able' and it should spawn Tar Beasts but I haven't seen any of them spawn. They do appear to generate correctly such as Fossil's Tar in the Overworld & Betweenlands Tar in the Betweenlands dimension... only the texture used is from Fossils.

I was thinking maybe Betweenlands could change their Tar name to 'swamptar' since their mod is swamp based & such... but if Fossils renames it on their side to 'fossiltar'... either way works since there wouldn't be any conflict.

**Comment by lindstheginj** [comment]
Duplicated in #1705 . Closing this one for housecleaning.
