### ISSUE TITLE
Volcano Biome Crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [FossilsArcheologyRevival/FossilsArcheologyRevival#1714]
There seems to be an issue between the volcano biome and OTG :(

Any help?

- https://paste.dimdev.org/pumuzilipa.mccrash

Can I disable the biome?

**Comment by RodrigoTaipe93** [comment]
After disabling it, still got a crash :(

Is there a way to change the ID? Could you add that? please :(

- https://paste.dimdev.org/reviratebi.mccrash

**Comment by Alex-the-666** [comment]
our biome ID's are dynamic and OTG's aren't. take this up with them.

**Comment by PG85** [comment]
Hey guys, OTG has been using dynamic biome id's for new worlds since OTG 1.12.2 v8. The only problems you might have is when you add/delete biome mods after world creation, which would affect the biome registry. If you have any problems or need help updating a legacy world, join us on the otg discord at https://discord.gg/UXzdVTH, thanks!
