### ISSUE TITLE
Velociraptor and deinonychus destroy the scratching posts when they hit it.

### ISSUE THREAD

**Issue by alfieboris** [FossilsArcheologyRevival/FossilsArcheologyRevival#1752]

**Comment by Conclure** [comment]
As said [here](https://fossils-archeology.fandom.com/wiki/Scratching_Post) the scratching post including the other enrichment items there is a chance certain dinosaurs may destroy it while playing with it due to too high damage/knockback. This include [Deinonychus](https://fossils-archeology.fandom.com/wiki/Deinonychus) and probably Velociraptor.
