### ISSUE TITLE
Request: Compatibility Underground Biomes Mod

### ISSUE THREAD

**Issue by Wolfram96** [FossilsArcheologyRevival/FossilsArcheologyRevival#1767]
The _underground biomes mod_ adds a number of different rock types including sedimentary rocks that have a small chance of dropping different fossils. I personally added your mod to my personal modded world because it has a number of very nicely textured living fossils like the nautilus and there are few mods that add fish that do not lag out my pc or that are as precise to restrict them to their natural habitat aka. rivers, swamps oceans, ... love your work. The fossil generation on the other hand kind of sucks, like the ore generation of minecraft in general. But hey there is always a tradeoff between realistic and fun.

**Anyway i'm not sure if this mod is still in active development but i would love to be able to analyse these fossils instead.** that way i could disable the regular fossil generation and search for sedimentary rock formations instead. Much more realistic if more time-consuming.

I not sure if thats possible but i would love to find Permafrost only underneath the grass in cold plains biomes?

**Comment by AechtRob** [comment]
You can add your required new recipes to the Analyser using CraftTweaker and build them for the undergroundbiomes fossil pieces instead of fossils own items:
https://github.com/FossilsArcheologyRevival/FossilsArcheology/wiki/CraftTweaker-Support

It will take a lot of individual recipes creating though :P

For the fossil ores in the main mod, there is an option in config to disable their generation, if you wanted to.

You'd have to find a way to add-back in some of the other drops from fossil blocks, or some other way to obtain these items if you need them in your pack: relic-scrap, bones, skull, ancient sword, scarab, helmet.

**Comment by Wolfram96** [comment]
oh thx i will look into this craft-tweaker thing, i just hope it doesn't involve writing code, since i suck at programming.

i personally don't really need the other items but i would just have to find them in the added ruins, i think there is a chance for them to be found that way.

its a mix between challenging caves & dungeons, medieval fantasy and peaceful building kind of thing and realism in terms of wold gen and how to find stuff is king. with archaeology as one of the leisure activities :)

thx for the quick reply

**Comment by AechtRob** [comment]
I'm just another user who was doing the same thing...... CraftTweaker isn't too bad once you get the gist of it. I did it easier for me though: what I did was remove the fossils and permafrost ores from generation, renamed the fossil one as a "fossil prepared for dissection" (or something like that) and used Craft Tweaker to generate a crafting recipe to turn the undergroundbiome fossils into that fossils block (which then gets smashed in the normal way for its normal drops). That was the least work.
