### ISSUE TITLE
Sitting Dinosaurs, Transforming Figurines, and Askew Dinopedia Models

### ISSUE THREAD

**Issue by OmniRat** [FossilsArcheologyRevival/FossilsArcheologyRevival#446]
I have noticed that whenever I save and quit a world and return to it, all dinosaurs automatically carry out the sit command, regardless of being tamed. In addition, when a chunk is unloaded, any tamed dinosaurs on said chunk will do the same thing, automatically sitting. I'm not sure if this is supposed to be a feature, but it can be annoying if you have large enclosures since the dinosaurs' hunger level seems to still decrease and they appear unable to feed themselves when in the sitting position.
I have also noticed that in my game when you break figurines and replace them they transform into completely different figurines. I have seen broken figurines turn into pristine zombie figurines and pristine steve figurines.
Finally, for me all of the Dinopedia models for the dinosaurs are pointed at a 45 degree angle toward the upper right-hand corner of the page with the front end facing away from the player.
Also I'm not sure if this is a glitch or not, but alligator gar and sturgeon don't spawn naturally in my world. I know that the nautilus and coelacanth are not able to naturally spawn at the moment, so is the same true for the other fish mobs or is something wrong?
The game version is 7.3.1

**Comment by PoetPlays** [comment]
Sitting dinosaurs is duplicate and fixed as per #425 

I for one have all "fish mobs" spawning in just fine and have not had an issue with this, including both nautilus and coelacanth, and have friends who have not been affected by that either, so I'm not sure if that's a global issue or just something your world is experiencing. Try loading up a new world with the mod, with no additional mods, and see if the issue is there.

**Comment by OmniRat** [comment]
Hooray for fixes!
I'll investigate the fish problem more, I have the suspicion that you are right and it has something to do with conflicting mods.
