### ISSUE TITLE
Mobs Starve while Playing with Toys

### ISSUE THREAD

**Issue by lindstheginj** [FossilsArcheologyRevival/FossilsArcheologyRevival#505]
"i keep having a ploblem with the mood system where like if i place a stratching Post or Tethered Log Etc the Prehistoric Creature will keep interacting with it and starve it self in the process so i have to manually Feed it" - wikia contributor

**Comment by Alex-the-666** [comment]
me irl

**Comment by Robomnz** [comment]
my raptors starve themselves by playing with their toys to much so i need to walk up to them and shove steak down their throats they also enjoy trying to eat the roof instead of food
![2017-12-28_17 04 22](https://user-images.githubusercontent.com/34904608/34400059-751ae7b6-ebf2-11e7-94c8-0fe92485a903.png)

![2017-12-28_16 58 06](https://user-images.githubusercontent.com/34904608/34400055-6ad1077c-ebf2-11e7-93fd-b5a8b66a0bca.png)

**Comment by Alex-the-666** [comment]
Closing all 1.7.10 issues for the time being
